### ISSUE TITLE
P0 issues with Cordova Extension

### ISSUE THREAD

**Issue by Chuxel** [Microsoft/vsts-cordova-tasks#26]
Issue 1: On Windows with the hosted agent, when no Cordova version is specified, the task seems to go and install Node 5 and then will error because it defaults to Cordova 5.3.3.  I think this is because the node boostrap code isn’t checking the version environment variable or taco.json but it also should not be downloading node 5 if node 0.12.7 is present which would be the case on the hosted agent anyway.

Issue 2: Specifying the version then results in this error:
3.	C:\LR\MMS\Services\Mms\TaskAgentProvisioner\Tools\agents\default\tasks\CordovaBuild\1.0.5\node-setup.js:24
4.	nodeSetupPromise.then(function () {
5.	^
6.	TypeError: Cannot read property 'then' of undefined
7.	at Object.<anonymous> (C:\LR\MMS\Services\Mms\TaskAgentProvisioner\Tools\agents\default\tasks\CordovaBuild\1.0.5\node-setup.js:24:17)
8.	at Module._compile (module.js:460:26)
9.	at Object.Module._extensions..js (module.js:478:10)
10.	at Module.load (module.js:355:32)
11.	at Function.Module._load (module.js:310:12)
12.	at Function.Module.runMain (module.js:501:10)
13.	at startup (node.js:129:16)
14.	at node.js:814:3

Issue 3: I am seeing errors with not being able to find model “q” in the command tasks.
16.	module.js:338
17.	throw err;
18.	^
19.	Error: Cannot find module 'q'
20.	at Function.Module._resolveFilename (module.js:336:15)
21.	at Function.Module._load (module.js:278:25)
22.	at Module.require (module.js:365:17)
23.	at require (module.js:384:17)
24.	at Object.<anonymous> (C:\LR\MMS\Services\Mms\TaskAgentProvisioner\Tools\agents\default\tasks\PhoneGapCommand\1.0.2\lib\node-manager.js:11:12)
25.	at Module._compile (module.js:460:26)
26.	at Object.Module._extensions..js (module.js:478:10)
27.	at Module.load (module.js:355:32)
28.	at Function.Module._load (module.js:310:12)
29.	at Module.require (module.js:365:17)

**Comment by Chuxel** [comment]
Fixed by https://github.com/Microsoft/vsts-cordova-tasks/pull/27
