### ISSUE TITLE
Cannot run CordovaCommand

### ISSUE THREAD

**Issue by eorengo** [Microsoft/vsts-cordova-tasks#57]
I have a TFS on premise.
I am trying to create a Build definition with a Cordova Command to add the Android platform in iOS. A very simple command call. I also could make it using a "Shell script" task.
Pls, find below the trace. Thanks!

2016-11-04T14:03:37.4538590Z ##[section]Starting: Cordova Command platform add android
 
2016-11-04T14:03:37.5194950Z ==============================================================================
 
2016-11-04T14:03:37.5202290Z Task         : Cordova Command
 
2016-11-04T14:03:37.5209150Z Description  : Run a Cordova CLI command
 
2016-11-04T14:03:37.5215960Z Version      : 1.3.9
 
2016-11-04T14:03:37.5222650Z Author       : Microsoft Corporation
 
2016-11-04T14:03:37.5229360Z Help         : [More Information](http://go.microsoft.com/fwlink/?LinkID=692058)
 
2016-11-04T14:03:37.5236120Z ==============================================================================
 
2016-11-04T14:03:38.4298120Z module.js:341
 
2016-11-04T14:03:38.4305860Z     throw err;
 
2016-11-04T14:03:38.4313000Z     ^
 
2016-11-04T14:03:38.4316400Z 
 
2016-11-04T14:03:38.4323360Z Error: Cannot find module './lib/vsts-task-lib-proxy.js'
 
2016-11-04T14:03:38.4330090Z     at Function.Module._resolveFilename (module.js:339:15)
 
2016-11-04T14:03:38.4337060Z     at Function.Module._load (module.js:290:25)
 
2016-11-04T14:03:38.4344100Z     at Module.require (module.js:367:17)
 
2016-11-04T14:03:38.4351530Z     at require (internal/module.js:16:19)
 
2016-11-04T14:03:38.4359090Z     at Object.<anonymous> (/Users/tecnweb/myagent/_work/_tasks/CordovaCommand_61ec6339-4a6a-4a69-875e-5a6f4db157a2/1.3.9/exec.js:8:19)
 
2016-11-04T14:03:38.4365950Z     at Module._compile (module.js:413:34)
 
2016-11-04T14:03:38.4376170Z     at Object.Module._extensions..js (module.js:422:10)
 
2016-11-04T14:03:38.4382920Z     at Module.load (module.js:357:32)
 
2016-11-04T14:03:38.4389800Z     at Function.Module._load (module.js:314:12)
 
2016-11-04T14:03:38.4397150Z     at Function.Module.runMain (module.js:447:10)
 
2016-11-04T14:03:38.6640200Z ##[error]Exit code 1 returned from process: file name '/Users/tecnweb/myagent/externals/node/bin/node', arguments '"/Users/tecnweb/myagent/_work/_tasks/CordovaCommand_61ec6339-4a6a-4a69-875e-5a6f4db157a2/1.3.9/exec.js"'.
 
2016-11-04T14:03:38.6706060Z ##[section]Finishing: Cordova Command platform add android

**Comment by jmatthiesen** [comment]
Which version of TFS are you using? I know some time has passed since you ask this question (sorry for the delay!), are you still having this problem?

**Comment by eorengo** [comment]
Hi Jordan!
I've tested on TFS2015 and also TFS'15' with the same results. Last week TFS15 was replace with TFS2017 RTM. We are changing to it but I don't think that something might change regarding Cordova.
Thanks.

**Comment by eorengo** [comment]
Hello Jordan,
The problem persist on TFS2017.
I said iOS (my bad). The agent is running in a MacOS and I am trying to run the Cordova project on it: add platform and build. Not working so far. 
module.js:341
    throw err;
    ^
Error: Cannot find module './lib/vsts-task-lib-proxy.js'

It seems something related to a proxy. Please, let me know if you need any additional info.
Thanks!

**Comment by dmitrii-snytkin** [comment]
Hello, @eorengo . Thanks for reporting and sorry for delay. We were not able to reproduce it locally using latest published version so we assume it has been already fixed. Could you please let us know if you still experiencing this issue? Thanks

**Comment by eorengo** [comment]
I gave up and I moved to Windows for Android apps. I plan to return it soon.
