### ISSUE TITLE
Issues with Ionic Command

### ISSUE THREAD

**Issue by RDalziel** [Microsoft/vsts-cordova-tasks#70]
When running ionic command without any version overrides & picking up ionic 3.2.0 with Cordova 7.0.1 i'm experiencing issues with lodash dependencies.

The command i'm running is : ionic cordova build --device --release

The error i receive is

2017-05-27T15:35:30.4182510Z Module cache at /Users/vso113307/.taco_home/node_modules
2017-05-27T15:35:33.4855550Z cordova already installed.
2017-05-27T15:35:33.4887710Z Cordova Module Path: /Users/vso113307/.taco_home/node_modules/cordova/7.0.1/node_modules/cordova
2017-05-27T15:35:33.5013130Z Module cache at /Users/vso113307/.taco_home/node_modules
2017-05-27T15:35:36.2175550Z ionic already installed.
2017-05-27T15:35:36.2365330Z Ionic Module Path: /Users/vso113307/.taco_home/node_modules/ionic/3.2.0/node_modules/ionic
2017-05-27T15:35:38.3174950Z { Error: Cannot find module 'lodash'
2017-05-27T15:35:38.3198060Z 
2017-05-27T15:35:38.3266470Z     at Function.Module._resolveFilename (module.js:469:15)
2017-05-27T15:35:38.3293730Z     at Function.Module._load (module.js:417:25)
2017-05-27T15:35:38.3332430Z     at Module.require (module.js:497:17)
2017-05-27T15:35:38.3365350Z     at require (internal/module.js:20:19)
2017-05-27T15:35:38.3408680Z     at Object.load (/Users/vso113307/.taco_home/node_modules/ionic/3.2.0/node_modules/ionic/node_modules/@ionic/cli-utils/dist/lib/modules.js:4:12)
2017-05-27T15:35:38.3461500Z     at Config.<anonymous> (/Users/vso113307/.taco_home/node_modules/ionic/3.2.0/node_modules/ionic/node_modules/@ionic/cli-utils/dist/lib/config.js:67:42)
2017-05-27T15:35:38.3506490Z     at throw (native)
2017-05-27T15:35:38.3553060Z     at rejected (/Users/vso113307/.taco_home/node_modules/ionic/3.2.0/node_modules/ionic/node_modules/@ionic/cli-utils/dist/lib/config.js:5:65) code: 'MODULE_NOT_FOUND' }

When i run the command manually via inline shell scripts i don't receive this error.

**Comment by dmitriy-petrishin** [comment]
Hi there.

I'm not completely understand where are you trying to put that command? 
Is that a local computer or cloud?

Please, give me more information.

**Comment by RDalziel** [comment]
This is using the VSTS Ionic Command Build Task Extension

**Comment by vovikdrg** [comment]
I have the same problem

**Comment by vovikdrg** [comment]
@RDalziel  Try to require version 3.4.0 of ionic, the put command as "cordova build android".
It was failing for me with 3.3.0 but today I tried with latest version and it just works

**Comment by dmitriy-petrishin** [comment]
@vovikdrg Yes, you are right about new ionic version.

@RDalziel I also would like to suggest you to add `npm` step with `npm install` command in your build configuration in VSTS.
<img width="654" alt="screen shot 2017-06-13 at 12 43 35 pm" src="https://user-images.githubusercontent.com/28645748/27076480-f854cdda-5035-11e7-88c4-814e0f0a7ad0.png">

For me it totally decided the problem.

**Comment by RDalziel** [comment]
I managed to get further with @vovikdrg suggestion - i've hit other problems with other updated pieces of the ionic framework but it seems this task does not work with ionic 3.3.0 and is resolved in 3.4.0.

@dmitriy-petrishin I do have NPM Install - it's a requirement for the rest of my build

**Comment by dmitriy-petrishin** [comment]
@RDalziel ok, that's good.
I'll close this issue, if you have another questions feel free to re-open or create new issue.
