### ISSUE TITLE
Cordova build error in vsts 

### ISSUE THREAD

**Issue by gaurijadhav509** [Microsoft/vsts-cordova-tasks#80]
Error in cordova build in vsts.
I am using empty build definition with 2 steps 
1) Cordova Build
2) Copy and Publish Artifacts
and cordova version 6.2.1

I am refering this article 
[https://docs.microsoft.com/en-gb/vsts/build-release/archive/apps/mobile/cordova-build](url)

This is the error

Starting: Cordova Build
******************************************************************************
==============================================================================
Task         : Cordova Build
Description  : Build a hybrid app project based on the Cordova CLI, Ionic CLI, TACO CLI, or other Cordova-compliant CLI
Version      : 1.3.11
Author       : Microsoft Corporation
Help         : [More Information](http://go.microsoft.com/fwlink/?LinkID=691186)
==============================================================================
d:\a\_tasks\CordovaBuild_70e94267-15dc-434d-8973-023d766825d7\1.3.11\lib\cordova-task.js:70
    process.chdir(cwd);
            ^
Error: ENOENT: no such file or directory, uv_chdir
    at Error (native)
    at processInputs (d:\a\_tasks\CordovaBuild_70e94267-15dc-434d-8973-023d766825d7\1.3.11\lib\cordova-task.js:70:13)
    at Object.<anonymous> (d:\a\_tasks\CordovaBuild_70e94267-15dc-434d-8973-023d766825d7\1.3.11\lib\cordova-task.js:32:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
Task failed

**Comment by drewgillies** [comment]
This is over 6 months old, so I'll go ahead and close it. If it's still a concern, please let me know.
